// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkdxwjbcfybypsotmqvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrZHh3amJjZnlieXBzb3RtcXZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2OTIxNzAsImV4cCI6MjA1NDI2ODE3MH0.UFlEMCE1JgKc5pShks2fxaxDbwsM1jp7bFNaN83yCxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);